sth went wrong in name identification!
EXCEPTION IN (/home/research/fame/common_scripts/main.py, LINE 53 "print("RESULT IS FUNNY: {}".format(result))"): local variable 'result' referenced before assignment
--------------------------------------------------
Identified names are: 
--------------------------------------------------
No search results are retrieved!
